services:
  postgres:
    image: postgres:16-alpine
    container_name: mytasks-postgres-test
    environment:
      POSTGRES_DB: mytasks
      POSTGRES_USER: mytasks
      POSTGRES_PASSWORD: mytasks
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_test:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/mock_data.sql:/docker-entrypoint-initdb.d/z_mock_data.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mytasks -d mytasks"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgrest:
    image: postgrest/postgrest:latest
    container_name: mytasks-postgrest-test
    ports:
      - "3001:3000"
    environment:
      PGRST_DB_URI: postgres://mytasks:mytasks@postgres:5432/mytasks
      PGRST_DB_SCHEMAS: public
      PGRST_DB_ANON_ROLE: web_anon
    depends_on:
      - postgres

volumes:
  postgres_data_test:
